export const PermissionsEnum = {
  ADMIN: 'A',
  SETTING: 'S',
  CREATE_PERMISSION: 'C00',
  PERMISSION_FETCH: 'FP01',
  PERMISSION_DETAILS: 'PD02',
  PERMISSION_CREATE: 'CP00',
  PERMISSION_UPDATE: 'UP00',
  PERMISSION_DELETE: 'DP00',
  ORG_EMPLOYEE_ALL: 'OE00',
  ORG_EMPLOYEE_FETCH: 'OE01',
  ORG_EMPLOYEE_DETAILS: 'OE02',
  ORG_EMPLOYEE_CREATE: 'OE03',
  ORG_EMPLOYEE_UPDATE: 'OE04',
  ORG_EMPLOYEE_DELETE: 'OE05',
  NOTIFICATION_PLAN_ALL: 'NP00',
  NOTIFICATION_PLAN_FETCH: 'NP01',
  NOTIFICATION_PLAN_DETAILS: 'NP02',
  NOTIFICATION_PLAN_CREATE: 'NP03',
  NOTIFICATION_PLAN_UPDATE: 'NP04',
  NOTIFICATION_PLAN_DELETE: 'NP05',
} as const;

export type PermissionCode = (typeof PermissionsEnum)[keyof typeof PermissionsEnum];
